import { useState } from 'react'
import axios from 'axios'
import Navbar from '../components/Navbar.jsx'
import CopyButton from '../components/CopyButton.jsx'
import { useAuth } from '../hooks/useAuth.jsx'
import {
  ShoppingBag, Sparkles, AlertCircle, CheckCircle,
  Tag, FileText, Search, Layers, Globe, Package
} from 'lucide-react'

const STEPS = ['Researching product', 'Generating content', 'Optimising for Shopify']

function Section({ title, icon: Icon, children, copyText }) {
  return (
    <div style={{
      border: '1px solid var(--grey-100)',
      borderRadius: 12,
      overflow: 'hidden',
      marginBottom: '1rem'
    }}>
      <div style={{
        padding: '0.875rem 1.25rem',
        background: 'var(--grey-50)',
        borderBottom: '1px solid var(--grey-100)',
        display: 'flex', alignItems: 'center', justifyContent: 'space-between'
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <Icon size={15} style={{ color: 'var(--orange)' }} />
          <span style={{ fontSize: 13, fontWeight: 600, color: 'var(--grey-700)' }}>
            {title}
          </span>
        </div>
        {copyText && <CopyButton text={copyText} label="Copy" variant="secondary" />}
      </div>
      <div style={{ padding: '1.25rem' }}>
        {children}
      </div>
    </div>
  )
}

export default function ShopifyPage() {
  const { deductCredit } = useAuth()
  const [brand, setBrand] = useState('')
  const [title, setTitle] = useState('')
  const [specs, setSpecs] = useState('')
  const [loading, setLoading] = useState(false)
  const [step, setStep] = useState(0)
  const [listing, setListing] = useState(null)
  const [error, setError] = useState('')

  const handleGenerate = async () => {
    setError('')
    setListing(null)
    setLoading(true)
    setStep(0)

    const stepInterval = setInterval(() => {
      setStep(s => (s + 1) % STEPS.length)
    }, 2500)

    try {
      const res = await axios.post('/api/shopify/generate', {
        brand, title, specs
      }, { withCredentials: true })
      setListing(res.data.listing)
      deductCredit()
    } catch (err) {
      setError(err.response?.data?.error || 'Generation failed. Please try again.')
    } finally {
      clearInterval(stepInterval)
      setLoading(false)
      setStep(0)
    }
  }

  const copyFullListing = () => {
    if (!listing) return
    const text = [
      `SHOPIFY PRODUCT LISTING`,
      `Generated by aLister · ${listing.generatedAt ? new Date(listing.generatedAt).toLocaleString() : 'now'}`,
      ``,
      `TITLE`,
      listing.title,
      ``,
      `META DESCRIPTION`,
      listing.metaDescription,
      ``,
      `SHORT DESCRIPTION`,
      listing.shortDescription,
      ``,
      `BULLET POINTS`,
      listing.bulletPoints?.map((b, i) => `${i + 1}. ${b}`).join('\n'),
      ``,
      `LONG DESCRIPTION`,
      listing.longDescription?.replace(/<[^>]+>/g, ''),
      ``,
      `SEO KEYWORDS`,
      listing.seoKeywords?.join(', '),
      ``,
      `SEARCH TAGS`,
      listing.searchTags?.join(', '),
      ``,
      `SHOPIFY COLLECTIONS`,
      listing.shopifyCollections?.join(', '),
      ``,
      `PRODUCT TYPE: ${listing.productType}`,
      `VENDOR: ${listing.vendor}`
    ].join('\n')
    navigator.clipboard.writeText(text)
  }

  return (
    <div style={{ minHeight: '100vh', background: 'var(--off-white)' }}>
      <Navbar />
      <div className="container" style={{ padding: '2.5rem 2rem', maxWidth: 860 }}>

        {/* Header */}
        <div style={{ marginBottom: '2rem' }}>
          <h1 style={{
            fontFamily: 'var(--font-display)',
            fontSize: 28, fontWeight: 700,
            color: 'var(--grey-900)', letterSpacing: '-0.5px', marginBottom: 8
          }}>
            Shopify Listing Generator
          </h1>
          <p style={{ fontSize: 15, color: 'var(--grey-500)' }}>
            Enter brand name, product title, and specifications — get a complete, SEO-optimised Shopify listing instantly.
          </p>
        </div>

        {/* Input card */}
        <div className="card" style={{ padding: '1.75rem', marginBottom: '1.5rem' }}>
          <div style={{ marginBottom: '1rem' }}>
            <label className="label">Brand Name *</label>
            <input
              className="input"
              value={brand}
              onChange={e => setBrand(e.target.value)}
              placeholder="e.g. Bottega Veneta"
            />
          </div>

          <div style={{ marginBottom: '1rem' }}>
            <label className="label">Product Title *</label>
            <input
              className="input"
              value={title}
              onChange={e => setTitle(e.target.value)}
              placeholder="e.g. Cassette Bag in Intrecciato Leather"
            />
          </div>

          <div style={{ marginBottom: '1.25rem' }}>
            <label className="label">Specifications *</label>
            <textarea
              className="input"
              value={specs}
              onChange={e => setSpecs(e.target.value)}
              placeholder="e.g. Material: Lambskin, Color: Cloud, Size: Medium (W30 x H18 x D8 cm), Hardware: Gold-tone, Condition: Pre-owned Excellent, Season: FW23, Made in Italy"
              rows={4}
              style={{ resize: 'vertical', lineHeight: 1.6 }}
            />
          </div>

          <div style={{ display: 'flex', justifyContent: 'flex-end' }}>
            <button
              className="btn btn-primary"
              onClick={handleGenerate}
              disabled={loading || !brand.trim() || !title.trim() || !specs.trim()}
              style={{ minWidth: 180, justifyContent: 'center' }}
            >
              {loading ? <span className="spinner" /> : <Sparkles size={15} />}
              {loading ? 'Generating...' : 'Generate Listing'}
            </button>
          </div>
        </div>

        {/* Loading steps */}
        {loading && (
          <div className="card fade-in" style={{ padding: '1.5rem', marginBottom: '1.5rem' }}>
            <div style={{ display: 'flex', gap: '1.5rem', alignItems: 'center' }}>
              {STEPS.map((s, i) => (
                <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                  {i < step ? (
                    <CheckCircle size={16} style={{ color: 'var(--success)' }} />
                  ) : i === step ? (
                    <span className="spinner spinner-orange" />
                  ) : (
                    <div style={{ width: 16, height: 16, borderRadius: '50%', background: 'var(--grey-200)' }} />
                  )}
                  <span style={{
                    fontSize: 13, fontWeight: i === step ? 600 : 400,
                    color: i <= step ? 'var(--grey-700)' : 'var(--grey-400)'
                  }}>{s}</span>
                  {i < STEPS.length - 1 && (
                    <div style={{ width: 24, height: 1, background: 'var(--grey-200)', marginLeft: 4 }} />
                  )}
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Error */}
        {error && (
          <div className="card fade-in" style={{
            padding: '1.25rem', marginBottom: '1.5rem',
            border: '1px solid #fecaca', background: 'var(--error-bg)',
            display: 'flex', gap: 10, alignItems: 'center', color: 'var(--error)'
          }}>
            <AlertCircle size={16} />
            <span style={{ fontSize: 14 }}>{error}</span>
          </div>
        )}

        {/* Listing output */}
        {listing && (
          <div className="fade-in">
            {/* Top bar */}
            <div style={{
              display: 'flex', alignItems: 'center', justifyContent: 'space-between',
              marginBottom: '1.25rem'
            }}>
              <div>
                <h2 style={{ fontSize: 16, fontWeight: 600, color: 'var(--grey-800)' }}>
                  Listing generated ✓
                </h2>
                <p style={{ fontSize: 12, color: 'var(--grey-400)', marginTop: 2 }}>
                  Enriched with: {listing.enrichedWith?.join(' + ')}
                </p>
              </div>
              <button className="btn btn-primary btn-sm" onClick={copyFullListing}>
                <CheckCircle size={13} /> Copy Full Listing
              </button>
            </div>

            {/* Title */}
            <Section title="Product Title" icon={FileText} copyText={listing.title}>
              <p style={{ fontSize: 16, fontWeight: 600, color: 'var(--grey-900)', lineHeight: 1.4 }}>
                {listing.title}
              </p>
              <p style={{ fontSize: 12, color: 'var(--grey-400)', marginTop: 6 }}>
                {listing.title?.length} characters
              </p>
            </Section>

            {/* Meta description */}
            <Section title="Meta Description (SEO)" icon={Globe} copyText={listing.metaDescription}>
              <p style={{ fontSize: 14, color: 'var(--grey-700)', lineHeight: 1.6 }}>
                {listing.metaDescription}
              </p>
              <p style={{ fontSize: 12, color: 'var(--grey-400)', marginTop: 6 }}>
                {listing.metaDescription?.length} / 160 characters
              </p>
            </Section>

            {/* Short description */}
            <Section title="Short Description (Above the Fold)" icon={FileText} copyText={listing.shortDescription}>
              <p style={{ fontSize: 14, color: 'var(--grey-700)', lineHeight: 1.7 }}>
                {listing.shortDescription}
              </p>
            </Section>

            {/* Bullet points */}
            <Section
              title="Bullet Points"
              icon={Layers}
              copyText={listing.bulletPoints?.map((b, i) => `• ${b}`).join('\n')}
            >
              <ul style={{ paddingLeft: 0, listStyle: 'none' }}>
                {listing.bulletPoints?.map((b, i) => (
                  <li key={i} style={{
                    display: 'flex', gap: 10, alignItems: 'flex-start',
                    padding: '6px 0',
                    borderBottom: i < listing.bulletPoints.length - 1 ? '1px solid var(--grey-50)' : 'none'
                  }}>
                    <div style={{
                      width: 20, height: 20, borderRadius: '50%',
                      background: 'var(--orange-faint)',
                      color: 'var(--orange)',
                      fontSize: 11, fontWeight: 700,
                      display: 'flex', alignItems: 'center', justifyContent: 'center',
                      flexShrink: 0, marginTop: 1
                    }}>
                      {i + 1}
                    </div>
                    <span style={{ fontSize: 14, color: 'var(--grey-700)', lineHeight: 1.6 }}>{b}</span>
                  </li>
                ))}
              </ul>
            </Section>

            {/* Long description */}
            <Section
              title="Long Description (HTML)"
              icon={FileText}
              copyText={listing.longDescription}
            >
              <div
                style={{ fontSize: 14, color: 'var(--grey-700)', lineHeight: 1.75 }}
                dangerouslySetInnerHTML={{ __html: listing.longDescription }}
              />
            </Section>

            {/* SEO Keywords */}
            <Section
              title="SEO Keywords"
              icon={Search}
              copyText={listing.seoKeywords?.join(', ')}
            >
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8 }}>
                {listing.seoKeywords?.map((kw, i) => (
                  <span key={i} className="tag" style={{
                    background: 'var(--orange-faint)',
                    color: 'var(--orange-dark)',
                    border: '1px solid var(--orange-subtle)'
                  }}>
                    {kw}
                  </span>
                ))}
              </div>
            </Section>

            {/* Search tags */}
            <Section
              title="Shopify Search Tags"
              icon={Tag}
              copyText={listing.searchTags?.join(', ')}
            >
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8 }}>
                {listing.searchTags?.map((t, i) => (
                  <span key={i} className="tag">{t}</span>
                ))}
              </div>
            </Section>

            {/* Collections + Product Type */}
            <div style={{ display: 'grid', gridTemplateColumns: '2fr 1fr', gap: '1rem' }}>
              <Section
                title="Shopify Collections"
                icon={Layers}
                copyText={listing.shopifyCollections?.join(', ')}
              >
                <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8 }}>
                  {listing.shopifyCollections?.map((c, i) => (
                    <span key={i} className="badge badge-orange">{c}</span>
                  ))}
                </div>
              </Section>

              <Section title="Product Type & Vendor" icon={Package}>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
                  <div>
                    <p style={{ fontSize: 11, fontWeight: 600, color: 'var(--grey-400)', marginBottom: 4 }}>
                      PRODUCT TYPE
                    </p>
                    <p style={{ fontSize: 14, fontWeight: 500, color: 'var(--grey-800)' }}>
                      {listing.productType}
                    </p>
                  </div>
                  <div>
                    <p style={{ fontSize: 11, fontWeight: 600, color: 'var(--grey-400)', marginBottom: 4 }}>
                      VENDOR
                    </p>
                    <p style={{ fontSize: 14, fontWeight: 500, color: 'var(--grey-800)' }}>
                      {listing.vendor}
                    </p>
                  </div>
                </div>
              </Section>
            </div>

            {/* Bottom copy all */}
            <div style={{ display: 'flex', justifyContent: 'center', marginTop: '1rem', paddingTop: '1rem', borderTop: '1px solid var(--grey-100)' }}>
              <button className="btn btn-primary" onClick={copyFullListing}>
                <CheckCircle size={15} /> Copy Full Listing to Clipboard
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
